kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --remote --init
  - git submodule foreach git pull origin master

- name: docker  
  image: plugins/docker
  settings:
    repo: tlemarchand/matrix-dimension
    target: app
    tags:
      - latest
      - build-${DRONE_BUILD_NUMBER}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
